

mutex_example:
	go run mutex_example.go


atomic_counter:
	go run atomic_counter.go

waitgroup_example:
	go run waitgroup_example.go


ticker_example:
	go run ticker_example.go

print_context:
	go run print_context.go


reflect_example:
	go run reflect_example.go

reflect_rule_example:
	go run reflect_rule_example.go
