

mutex_example:
	go run mutex_example.go


atomic_counter:
	go run atomic_counter.go

waitgroup_example:
	go run waitgroup_example.go


ticker_example:
	go run ticker_example.go

print_context:
	go run print_context.go


reflect_example:
	go run reflect_example.go

reflect_rule_example:
	go run reflect_rule_example.go

range_channel_example:
	go run range_channel_example.go

channel_select_1_example:
	go run channel_select_1_example.go

channel_select_2_example:
	go run channel_select_2_example.go

context_deadline_example:
	go run context_deadline_example.go

singleflight_example:
	go run singleflight_example.go

stop_goroutine_1_example:
	go run	stop_goroutine_1_example.go

stop_goroutine_2_example:
	go run	stop_goroutine_2_example.go

context_copy_example:
	go run context_copy_example.go

struct_method_ptr_or_not_example:
	go run struct_method_ptr_or_not_example.go

string_array_example:
	go run string_array_example.go

ref_ptr_struct_print_example:
	go run ref_ptr_struct_print_example.go

func_return_val_init_example:
	go run func_return_val_init_example.go

struct_init_example:
	go run struct_init_example.go

interface_struct_copy_example:
	go run interface_struct_copy_example.go

slice_goroutine_example:
	go run slice_goroutine_example.go

recover_global_example:
	go run recover_global_example.go

	echo "============================================================================================================"
	echo "============================================================================================================"

	go run recover_global_example2.go

	echo "============================================================================================================"
	echo "============================================================================================================"

	go run recover_global_example3.go

goroutine_timeout_exit_example:
	go run goroutine_timeout_exit_example.go

return_defer_order:
	go run return_defer_order.go
