

mutex_example:
	go run mutex_example.go


atomic_counter:
	go run atomic_counter.go

waitgroup_example:
	go run waitgroup_example.go


ticker_example:
	go run ticker_example.go

print_context:
	go run print_context.go


reflect_example:
	go run reflect_example.go

reflect_rule_example:
	go run reflect_rule_example.go

range_channel_example:
	go run range_channel_example.go

channel_select_1_example:
	go run channel_select_1_example.go

channel_select_2_example:
	go run channel_select_2_example.go

context_deadline_example:
	go run context_deadline_example.go
