

exec_func_tuple_example:
	g++ exec_func_tuple_example.cpp -std=c++14



object_pool_example:
	g++ object_pool_example.cpp -std=c++11 -o object_pool_example.out
	./object_pool_example.out

count_down_latch_example:
	g++ count_down_latch_example.cpp -std=c++11 -o count_down_latch_example.out
	./count_down_latch_example.out


safe_cast_test:
	g++ safe_cast_test.cpp -std=c++11 -o safe_cast_test.out
	./safe_cast_test.out

BaseAspect_example:
	g++ BaseAspect_example.cpp -std=c++11 -o BaseAspect_example.out
	./BaseAspect_example.out

log_test:
	g++ log_test.cpp -std=c++11 -o log_test.out
	./log_test.out
