

exec_func_tuple_example:
	g++ exec_func_tuple_example.cpp -std=c++14



object_pool_example:
	g++ object_pool_example.cpp -std=c++11 -o object_pool_example.out
	./object_pool_example.out

count_down_latch_example:
	g++ count_down_latch_example.cpp -std=c++11 -o count_down_latch_example.out
	./count_down_latch_example.out


safe_cast_test:
	g++ safe_cast_test.cpp -std=c++11 -o safe_cast_test.out
	./safe_cast_test.out
