
FROM ubuntu:18.04

LABEL maintainer="Daidai <daidai4269@aliyun.com>"


RUN apt-get update && apt-get -y upgrade && apt-get -y install wget

RUN apt-get update \
 && apt-get install -y \
    curl \
    git \
    make \
    ninja-build \
    software-properties-common \
    vim \
    wget

RUN apt-get -y --no-install-recommends install \
    aptitude \
    bash-completion \
    build-essential \
    clang-${LLVM_VERSION} \
    cmake \
    cmake-curses-gui \
    coreutils \
    gcc \
    g++ \
    gdb \
    git-core \
    htop \
    mercurial \
    ncdu \
    ninja-build \
    python \
    python-dev \
    python-pip \
    python-software-properties \
    software-properties-common \
    subversion \
    tmux \
    tree \
    unzip \
    vim
