
cond_example:
	go run cond_example.go
map_example:
	go run map_example.go
mutex_example:
	go run mutex_example.go
once_example:
	go run once_example.go
pool_example:
	go run pool_example.go
rwmutex_example:
	go run rwmutex_example.go
waitgroup_example:
	go run waitgroup_example.go
